### ISSUE TITLE
Can't edit the snippet I created

### ISSUE THREAD

**Issue by conradj** [gavJackson/Cyrus-App#4]
![image](https://user-images.githubusercontent.com/4677569/45920589-5847a280-be9e-11e8-954f-aa753aa50261.png)

Selected the last one. Text boxes are blank.

![image](https://user-images.githubusercontent.com/4677569/45920592-63023780-be9e-11e8-9adb-d236749041aa.png)

The precreated ones work.

**Comment by gavJackson** [comment]
Ah good catch, i have been able to replicate, its something to do with being in that initial state of having no snippets (hence the two example ones above) - somehow that breaks snippet editing.  Cheers
